name: 'GitHub Actions Youthstudy Bot'
on:
  workflow_dispatch:
    inputs:
      previous:
        description: '是否打卡往期课程(true/false)'
        required: true
        default: 'false'
  schedule:
    # UTC4:00(北京UTC+8 12:00点)触发任务
    - cron: '0 4 * * *'

env:
  push: true
  way: 'mid' #选择mid或者xLitemallToken

jobs:
  youthstudymark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Add xLitemallToken to python file
        if: env.way == 'xLitemallToken'
        run: sed -i '1i\xLitemallToken="${{ secrets.xLitemallToken }}"' main.py

      - name: Add mid to python file
        if: env.way == 'mid'
        run: sed -i '1i\mid=${{ secrets.MID }}' main.py

      - name: Add push token
        if: env.push == 'true'
        run: sed -i '1i\token="${{ secrets.PUSHTOKEN }}"' push.py

      - name: Set up env
        run: pip install -r requirement.txt
          
      - name: Run main command
        run: python main.py

      - name: Submit previous activity
        if: github.event.inputs.previous == 'true'
        run: python previous.py

      - name: Push result to Wechat by pushplus
        if: env.push == 'true'
        run: python push.py
