name: 'GitHub Actions Youthstudy Bot'
# UTC17:00(北京UTC+8 01:00点)触发任务
on:
  push:
  schedule:
    - cron: '0 17 * * *'

jobs:
  youthstudymark:
    runs-on: ubuntu-latest
    steps:
      - name: checkout actions
        uses: actions/checkout@v1

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Add xLitemallToken to python file
        run: sed -i '1i\xLitemallToken="${{ secrets.xLitemallToken }}"' main.py
      
      - name: Set up env
        run: pip install -r requirement.txt
          
      - name: command
        run: |
          python main.py
